@startuml game_states

[*] --> City

City -> Outside : LEAVE
City --> City : BUY

Outside --> Outside : SEARCH (failed)
Outside --> Battle : SEARCH (success)
Outside --> City : RETREAT

Battle --> Battle : BATTLE\nFLEE (failed)
Battle --> Outside : BATTLE (won)\nFLEE (success)
Battle --> City : BATTLE (lost)

@enduml
